// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrdsB2hP2We9QDaAwDpgLCcxDW8ajpQs',
    appId: '1:770437579780:web:e903821c4d7e44ce77e151',
    messagingSenderId: '770437579780',
    projectId: 'look-c1bf8',
    authDomain: 'look-c1bf8.firebaseapp.com',
    databaseURL: 'https://look-c1bf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'look-c1bf8.appspot.com',
    measurementId: 'G-76GKHZ0MJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdrdsB2hP2We9QDaAwDpgLCcxDW8ajpQs',
    appId: '1:770437579780:android:90e8a92cd9b1c5de77e151',
    messagingSenderId: '770437579780',
    projectId: 'look-c1bf8',
    databaseURL: 'https://look-c1bf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'look-c1bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVsrlFKkWyJBV73AyXOmt0S9J2JcoGXy4',
    appId: '1:770437579780:ios:f1b20a69b4cf9d0677e151',
    messagingSenderId: '770437579780',
    projectId: 'look-c1bf8',
    databaseURL: 'https://look-c1bf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'look-c1bf8.appspot.com',
    iosBundleId: 'com.looook.looook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVsrlFKkWyJBV73AyXOmt0S9J2JcoGXy4',
    appId: '1:770437579780:ios:3e41d8fc8c714fa577e151',
    messagingSenderId: '770437579780',
    projectId: 'look-c1bf8',
    databaseURL: 'https://look-c1bf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'look-c1bf8.appspot.com',
    iosBundleId: 'com.example.look',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNaYMH7190dTnjQUjnCLNp-6ilzde6cFg',
    appId: '1:770437579780:web:58798f32b336b08677e151',
    messagingSenderId: '770437579780',
    projectId: 'look-c1bf8',
    authDomain: 'look-c1bf8.firebaseapp.com',
    databaseURL: 'https://look-c1bf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'look-c1bf8.appspot.com',
    measurementId: 'G-X2XTRWEPNH',
  );

}